version: "3"
services:
  line-webhook:
    build: .
    image: ghcr.io/eventmod/webhook:lasted
    restart: unless-stopped
    container_name: "line-webhook"
    ports:
      - "5000:5000"
networks:
  default:
    external:
      name: eventmod-network