version: "3"
services:
  line-webhook:
    build: .
    image: ghcr.io/eventmod/webhook:latest
    container_name: "line-webhook"
    ports:
      - "5000:5000"
    restart: always
networks:
  default:
    external:
      name: eventmod-network